### PR TITLE
Fixed build by adding glide spec, add AWS CloudBuild support

### PR DESCRIPTION
**Pull request by whereisaaron**
In order to make changes I needed to get the project building. There were two problems:
1. The current go-client alpha is in the middle of breaking changes, I needed to peg the previous version, so I added a glide.yaml/glide.lock to enable that.
2. I added automated build, container build, and push to Docker Hub support using AWS CloudBuild.
I haven't changed the functionality at all in the PR. I'll do seperate PR's for that. This is just for clean, automated builds.

### CODE REVIEW

**Comment by luna-duclos** [comment]
+1 on the vendor changes
 not sure how I feel on the AWS stuff yet, need to give it a good read. Wondering if we also want to support the google equivalent of this.

**Comment by luna-duclos** [comment]
Been pondering about this, would you find it reasonable to move all the AWS specific stuff to a subfolder called `aws/` ? Mainly so that things don't get confusing if we add support for other cloud builders later on

**Comment by whereisaaron** [comment]
I wondered about including it at all. But then the barrier to contributing is mostly having an easy way to build and test changes. So I thought better to share. I'd like to see some build instructions added to the README.

I can move it where you like, except that `buildspec.yml` does need to be in the root of the repo to work with CodeBuild. I'd suggest a `/codebuild` so e.g. you can have a `/travisci`, `/codeship`, `/teamcity` folder if people have build specs for those.

I'll reorganize it.

**Comment by whereisaaron** [comment]
I have shifted everything except `buildspec.yml` into a `codebuild` folder with its own `README.md`. Added a link to `README.md` in the root `README.md`. I marked the existing, local build `build.sh` and `build-container.sh` scripts as executable.

**Comment by whereisaaron** [comment]
@luna-duclos my `-class` branch in on top of this codebuild branch, so I'll wait until you decide on this PR before doing the next PR

**Comment by luna-duclos** [comment]
I'll try and look at this in the morning, been busy over the weekend

**Pull request merged**
