### PR TITLE
Remove kubectl-proxy and bump alpine ver

### PR DESCRIPTION
**Pull request by nanliu**
* Use hyperkube instead of custom kubectl proxy
* Bump alpine version to 3.5

### CODE REVIEW

**Comment by nanliu** [comment]
I know #50 will ultimately remove kubectl-proxy, but in this case we don't even need a custom dockerfile to do this and we can use hyperkube instead (which is kept up to date).

**Comment by euank** [comment]
I'm hopeful #50 will be merged soon enough that we can skip this.

And the hyperkube image is something like 300MB larger, so it's not all good.

**Comment by nanliu** [comment]
Sounds reasonable, feel free to close this PR if #50 is going to land soon.

**Comment by euank** [comment]
The alpine version bump still would make sense I think if you want to PR that alone.

Thanks!

**Pull request closed without merging**
