### PR TITLE
Update documentation and certificate-type from TPR to CRD

### PR DESCRIPTION
**Pull request by jlcrow**
Update docs and k8s yaml to use custom resource definition since TPR is
deprecated in 1.7 and removed in 1.8 of Kubernetes

### CODE REVIEW

**Comment by hsingh6764** [comment]
@jlcrow hey do u have working(full) deployment config for kube-cert-manager

**Comment by jlcrow** [comment]
@hsingh6764 You can find my deployment here:  [https://github.com/GreatWebGuy/kube-cert-manager-deployment](https://github.com/GreatWebGuy/kube-cert-manager-deployment) I've removed the provider integration from the deployment so you would need to set up credentials and environment variables and secret in the deployment. I've added the 0.5.0 docker image to my personal repo [https://hub.docker.com/r/jlcrow/kube-cert-manager/](https://hub.docker.com/r/jlcrow/kube-cert-manager/)

**Comment by luna-duclos** [comment]
Thanks a lot for this!

**Comment by rochdev** [comment]
Any idea when this will be released? We are starting new clusters and would like to use kubernetes 1.8

**Comment by rochdev** [comment]
Just noticed there were no code changes. Does that mean the new custom resource type is compatible with the 0.3.1 image?

**Comment by jlcrow** [comment]
@rochdev Yes all my changes were to documentation. I did a build of latest master, haven't tried running on 0.3.1.  The CustomResourceDefinition and ThirdPartyResource work the same way in the api, so if you're just looking to go to 1.8 and need that support using the CRD instead of the TPR should work.

**Pull request merged**
