### PR TITLE
gc: allow disabling secret gc with a flag

### PR DESCRIPTION
**Pull request by euank**
Related to #45, for those of us who just don't want to delete at all.

### CODE REVIEW

**Comment by luna-duclos** [comment]
Am not entirely happy with this change, I'd prefer a single gc flag that lets us set the timer to either `no`, or a time.Duration, and would default to `7d`

**Comment by euank** [comment]
Changed to be a duration, good call.

**Comment by luna-duclos** [comment]
A few more slight things:

1) Let's have any zero or negative duration disable the GC (Should just be a matter of removing the if on startup I think ?)
2) The documentation needs to be updated

**Comment by euank** [comment]
The 0s thing is just me being wary of the zero value, but since `flag` defaults it anyway it was overly cautious.

I think I got all the relevant docs. Let me know if I missed any others.

**Comment by luna-duclos** [comment]
Will check this in detail in the next day or two

**Comment by luna-duclos** [comment]
Have given this a good read, and I don't think this will behave as people expect it to, a secret can still get deleted within a day if the GC happens to trigger the day after. 
As #45 suggests, we should probably record the time a secret goes unused and use that as the threshold, and meanwhile also leave the option in to disable GC entirely.

Is this a change you'd want to work on ? The current flag is useful regardless, so I'm ok with it if you aren't.

**Comment by euank** [comment]
My initial pr to disable GC was with the intent of later coming back and doing #45. I'm happy to do it properly in one go instead, it'll just take longer for me to find the spare cycles.

**Comment by luna-duclos** [comment]
Thank you!

**Pull request closed without merging**
