### PR TITLE
Save and retrieve user-info based on email alone

### PR DESCRIPTION
**Pull request by ean**
This will avoid hitting the registration rate-limit if kube-cert-manager is
initially set up to request certificates for many different domains.

### CODE REVIEW

**Comment by luna-duclos** [comment]
How does this behave when deploying on an already running db? I assume it will resolve the challenge on the next refresh seeing as they were previously bound to domains ?

**Comment by AlecTroemel** [comment]
any update on this? I'm hitting rate limits on creating new accounts a lot..

**Comment by ean** [comment]
Sorry, I have not had time to follow up on this. And we have internally moved over to [cert-manager](https://github.com/jetstack/cert-manager). Which gives us better control og the certificate issuing, and it seems to behaving a lot better in all the corner cases where I have seen kube-cert-manager act up. 

@luna-duclos the current patch does not preserve the users that are linked to the different domains. I will close this. If anybody want to pick it up and fix it, be my guest!

**Comment by AlecTroemel** [comment]
thanks @ean thanks for the response. cert-manager does seem like the preferred solution now days

**Pull request closed without merging**
